Create session schema
hack4impact-uiuc/academy-hw-study-buddies pull request #16
Opened 2021-11-05 03:11 UTC by gracewzhang

#2

2021-11-10 16:34 UTC, dyang5200 requested changes
Good work Grace and Eesha! Just mostly style changes. You'll be able to merge after making changes and testing that all your endpoints work as expected!

2021-11-10 16:34 UTC, dyang5200 commented on api/src/api/session.js
> +// uncomment to use the schema
Remove comment

2021-11-10 16:34 UTC, dyang5200 commented on api/src/api/session.js
> +const isValidMongoId = (id) => ObjectId.isValid(id);
You can remove everything that has to do with validMongoId. We don't really need this, and SSW is looking to remove this from their code too. Anonymous current SSW TL added this last semester to "try to be cool" (a direct quote) but ultimately decided it's extra

2021-11-10 16:34 UTC, dyang5200 commented on api/src/api/session.js
> +        message: 'Successfully created new session',
Capitalize the 'S' in Session

2021-11-10 16:34 UTC, dyang5200 commented on api/src/api/session.js
> +      message: `Successfully retrieved all resources.`,
This should be Sessions, not Resources

2021-11-10 16:34 UTC, dyang5200 commented on api/src/api/session.js
> +    }
Same as earlier, remove every isValidMongoId check

2021-11-10 16:34 UTC, dyang5200 commented on api/src/api/session.js
> +
Remove empty line

2021-11-10 16:34 UTC, dyang5200 commented on api/src/models/session.js
> +  timeout: { type: Number, default: 43200 }, // length of timeout in milliseconds, 12 hours
Comment should say `seconds` not `milliseconds` since you divided by 1000. Either update the comment, or take out the dividing by 1000

2021-11-10 16:34 UTC, dyang5200 commented on api/src/api/session.js
> +      { new: true, runValidators: true },
This line is also unnecessary I think. Try removing it and see if it gives you any errors

2021-11-10 16:34 UTC, dyang5200 commented on api/src/models/session.js
> +  groupSize: { type: Number, default: 0 },
Can remove groupSize as discussed earlier :)

2021-11-11 22:34 UTC, ashwin1104 requested changes
Awesome job guys :) just a couple changes

2021-11-11 22:34 UTC, ashwin1104 commented on api/src/app.js
> +
Our backend server actually starts up in `api/bin/www` when we run `yarn start`, so this will be a duplicate listener. We can remove the changes for this file.

2021-11-11 22:34 UTC, ashwin1104 commented on api/src/api/session.js
> +import { ObjectId } from 'mongodb';
you can remove this import since we're removing isValidMongoId as well

2021-11-12 00:12 UTC, gracewzhang commented on api/src/api/session.js
> +      { new: true, runValidators: true },
which line is this referring to?

2021-11-12 03:33 UTC, dyang5200 commented on api/src/api/session.js
> +      { new: true, runValidators: true },
79 sorry. I don't know why it selected 3 lines

2021-11-12 03:49 UTC, dyang5200 approved these changes
Awesome job Eesha and Grace! 💯

2021-11-12 03:53 UTC, ashwin1104 approved these changes

2021-11-12 03:53 UTC, merged