Create database schema and add classes field
hack4impact-uiuc/academy-hw-study-buddies pull request #17
Opened 2021-11-05 03:21 UTC by jessicasingh7

## Status:

## Description

Fixes #<number>

## Todos

## Screenshots

2021-11-10 16:58 UTC, dyang5200 requested changes
Looks great Anthony and Jessica! Let me know if you have any questions about my comments!

2021-11-10 16:58 UTC, dyang5200 commented on api/src/models/user.js
> +    type: [String],
Add a `default` field for the default value a user's `classes` property should be if they've added no classes.

2021-11-10 16:58 UTC, dyang5200 commented on api/src/api/user.js
> +
Please remove all comments that don't pertain to the code

2021-11-10 16:58 UTC, dyang5200 commented on api/src/api/user.js
> +
Please remove empty line

2021-11-10 16:58 UTC, dyang5200 commented on api/src/api/user.js
> +      message: 'Successfully retrieved users',
Add 'Successfully retrieved all users' to make it clear that we're getting all users

2021-11-10 16:58 UTC, dyang5200 commented on api/src/api/user.js
> +    if (updatedUser) {
Add an if statement above this that handles the case where we can't find the user with the id that was inputted

2021-11-10 16:58 UTC, dyang5200 commented on api/src/api/user.js
> +    res.status(200).json({
Same as above. Handle the case when the user with the id was not found, and only return a successful response when the user with the id was successfully found

2021-11-11 22:56 UTC, ashwin1104 requested changes
Looks good to me! Nice job with the endpoints. Just left one change for you guys to address:

2021-11-11 22:56 UTC, ashwin1104 commented on api/src/app.js
> +});
We can remove this since we already have a listener. When you run `yarn start`, the api/bin/www script runs. That script includes a listener that starts the backend server.

2021-11-12 03:46 UTC, dyang5200 approved these changes
Great job! 💯

2021-11-12 03:58 UTC, ashwin1104 approved these changes

2021-11-12 04:03 UTC, merged