Eesha issue 14
hack4impact-uiuc/academy-hw-study-buddies pull request #19
Opened 2021-11-14 21:45 UTC by eeshabarua

## Status:

🚧 

## Description

I wrote a function in apiWrapper to call a put request on the classes field in User. 

Fixes #<number>

## Todos

I want to stylize the card css to create a right-side delete icon and clean up the feature. I also want to build out the functionality of the put request in the frontend.

## Screenshots

![image](https://user-images.githubusercontent.com/61480751/141699804-ab782751-18a9-45b7-9720-19a95dc85db6.png)

2021-11-16 07:21 UTC, dyang5200 requested changes
Good start Eesha! Looks like a few things still need to be fixed before this is ready. Let me know if you have any questions!

2021-11-16 07:21 UTC, dyang5200 commented on client/src/css/Classes.scss
> +@import '../styles/colors.scss';
Remove this file since it's not being used.

2021-11-16 07:21 UTC, dyang5200 commented on client/src/components/ClassCard.jsx
> +// import '../css/Class.scss';
Remove comment

2021-11-16 07:21 UTC, dyang5200 commented on client/src/utils/apiWrapper.js
> +export const putUserClass = (body) => {
give this a more descriptive name. putUserClass isn't intuitive on the frontend. change to `editUserClasses` or something similar

2021-11-16 07:21 UTC, dyang5200 commented on client/src/components/ClassCard.jsx
> +    <Card style={{ height: '85px' }}>
For best practices, you should never have inline styling. Extract styles to a separate scss file

2021-11-16 07:21 UTC, dyang5200 commented on client/src/components/ClassCard.jsx
> +  const { text } = props;
This variable name is not descriptive enough. `Text` is ambiguous; give it a more descriptive name that describes what the text is

2021-11-16 07:21 UTC, dyang5200 commented on client/src/components/ClassCard.jsx
> +        </Button>
Change `Delete` to an `x` for aesthetic purposes. Also, the delete button should be on the same line as the button text. Another thing, the syntax for onclick functions are like this: `onClick`. Make sure to test your code and look up documentation to make sure all of it is working as you intend it.

2021-11-16 07:21 UTC, dyang5200 commented on client/src/pages/Profile.jsx
> +        <ClassCard text={'CS225'} />
This is repetitive code. Please use a .map() function to modularize your code like we talked about in lessons.

2021-11-17 10:24 UTC, ashwin1104 requested changes
Nice work Eesha, very clean code! Left some important changes for you to address. Also change the title of your PR to the commit message conventions we mentioned (starting with an imperative verb, briefly describe purpose of PR). Example: Create ClassCard component.

2021-11-17 10:24 UTC, ashwin1104 commented on client/src/utils/apiWrapper.js
> +export const editUserClasses = (body) => {
sweet

2021-11-17 10:24 UTC, ashwin1104 commented on client/src/css/ClassCard.scss
> +}
Add a new line here. It's formatting standards to have a new line at the end of each file

2021-11-17 10:24 UTC, ashwin1104 commented on client/src/components/ClassCard.jsx
> +        <Button basic color="red" onClick={ editUserClasses() }>X</Button>
Change `onClick={ editUserClasses() }` to `onClick={editUserClasses}` (i.e. remove the parentheses). Let's discuss the reasoning in person

2021-11-17 10:24 UTC, ashwin1104 commented on client/src/components/ClassCard.jsx
> +    <Card>
Make the styling changes I suggested for a cleaner look:
- shrink the X button and move it closer to the right-hand-side
- enlarge the classCardText
- center the classCardText in the card

![ClassCardBasicSketch](https://user-images.githubusercontent.com/34987983/142182329-e29b8249-ee1b-4bdb-84e6-e6c4511df2ab.jpg)

2021-11-18 00:26 UTC, dyang5200 approved these changes
Great :)

2021-11-18 00:27 UTC, ashwin1104 approved these changes

2021-11-18 00:28 UTC, merged