Classes Page - Anthony
hack4impact-uiuc/academy-hw-study-buddies pull request #32
Opened 2021-11-24 23:01 UTC by saxytony

## Status:

## Description
Map class data to individual cards that show course name and all members in the course. Cards are centered on page with flex-start positioning and 4 cards per row.

Fixes #<number>

## Todos

## Screenshots
![image](https://user-images.githubusercontent.com/90807954/143323344-cfe50468-726c-44cb-b3c2-7d80d5e19f60.png)

2021-11-26 02:06 UTC, ashwin1104 requested changes
This looks really good. Super clean code too (esp CSS)! Make these minor changes and then you're good to merge 🚀

2021-11-26 02:06 UTC, ashwin1104 commented on client/src/css/ClassPageCard.scss
> +}
Add new line to this file

2021-11-26 02:06 UTC, ashwin1104 commented on client/src/components/ClassPageCard.jsx
> +      <Card className="class-cards">
nitpick but change className to "class-card" since it just applies to a singular card

2021-11-26 02:06 UTC, ashwin1104 commented on client/src/components/ClassPageCard.jsx
> +            {classMembers.map((name) => (
`name` is not necessarily a stable attribute to use as a key (in case there's two Anthony Cruz Mecados some time in the future, who knows). Instead, change to `classMembers.map((name, index) =>` and set the `<p>` key to `index`.
https://reactjs.org/docs/lists-and-keys.html#keys

2021-11-26 02:06 UTC, ashwin1104 commented on client/src/pages/Classes.jsx
> +        {Object.keys(classes_members).map((key, i) => (
use this same `map((value, index) =>` format for the ClassPageCard component

2021-11-27 04:11 UTC, dyang5200 approved these changes
Great work Anthony! It looks SO good. +1 to Ashwin's comments, and change that one css class name and you should be good to merge! Amazing 💯

2021-11-27 04:11 UTC, dyang5200 commented on client/src/components/ClassPageCard.jsx
> +      <Card className="class-cards">
Actually please change it to class-page-card since there is already a class-card for the class cards on the profile page

2021-12-02 04:48 UTC, saxytony reviewed
All requested changes resolved

2021-12-02 16:36 UTC, ashwin1104 approved these changes

2021-12-03 03:23 UTC, merged